export const WS_FEED_ORDERS_CONNECT : 'WS_FEED_ORDERS_CONNECT' = 'WS_FEED_ORDERS_CONNECT';
export const WS_USER_ORDERS_CONNECT : 'WS_USER_ORDERS_CONNECT' = 'WS_USER_ORDERS_CONNECT';

export const WS_FEED_RECEIVED_MESSAGE : 'WS_FEED_RECEIVED_MESSAGE' = 'WS_FEED_RECEIVED_MESSAGE';

export const WS_FEED_ORDERS_ERROR : 'WS_FEED_ORDERS_ERROR' = 'WS_FEED_ORDERS_ERROR';

export const WS_FEED_ORDERS_DISCONNECT : 'WS_FEED_ORDERS_DISCONNECT' = 'WS_FEED_ORDERS_DISCONNECT';
export const WS_USER_ORDERS_DISCONNECT : 'WS_USER_ORDERS_DISCONNECT' = 'WS_USER_ORDERS_DISCONNECT';

export const GET_ORDER : 'GET_ORDER' = 'GET_ORDER'
