export const GET_INGREDIENTS_REQUEST : 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS : 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED : 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED';
export const INCREMENT_IGREDIENT_COUNT : 'INCREMENT_IGREDIENT_COUNT' = 'INCREMENT_IGREDIENT_COUNT';
export const DECREMENT_IGREDIENT_COUNT : 'DECREMENT_IGREDIENT_COUNT' = 'DECREMENT_IGREDIENT_COUNT';
export const RESET_INGREDIENTS_COUNT: 'RESET_INGREDIENTS_COUNT' = 'RESET_INGREDIENTS_COUNT';
export const CHANGE_BUNS_COUNT : 'CHANGE_BUNS_COUNT' = 'CHANGE_BUNS_COUNT';