export const POST_ORDER_REQUEST : 'POST_ORDER_REQUEST' = 'POST_ORDER_REQUEST';
export const POST_ORDER_SUCCESS : 'POST_ORDER_SUCCESS' = 'POST_ORDER_SUCCESS';
export const POST_ORDER_FAILED : 'POST_ORDER_FAILED' = 'POST_ORDER_FAILED';
export const TOGGLE_ORDER_DATA : 'TOGGLE_ORDER_DATA' = 'TOGGLE_ORDER_DATA';
