export const REGISTER_SUCCESS : 'REGISTER_SUCCESS' = 'REGISTER_SUCCESS';
export const REGISTER_FAILED : 'REGISTER_FAILED' = 'REGISTER_FAILED';

export const AUTH_SUCCESS : 'AUTH_SUCCESS' = 'AUTH_SUCCESS';
export const AUTH_FAILED : 'AUTH_FAILED' = 'AUTH_FAILED';

export const SEND_EMAIL_REQUEST : 'SEND_EMAIL_REQUEST' = 'SEND_EMAIL_REQUEST';
export const SEND_EMAIL_SUCCESS : 'SEND_EMAIL_SUCCESS' = 'SEND_EMAIL_SUCCESS';
export const SEND_EMAIL_FAILED : 'SEND_EMAIL_FAILED' = 'SEND_EMAIL_FAILED';

export const RESET_PASSWORD_REQUEST : 'RESET_PASSWORD_REQUEST' = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS : 'RESET_PASSWORD_SUCCESS' = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED : 'RESET_PASSWORD_FAILED' = 'RESET_PASSWORD_FAILED';

export const LOGOUT_USER : 'LOGOUT_USER' = 'LOGOUT_USER';
export const SET_USER_DATA : 'SET_USER_DATA' = 'SET_USER_DATA';